name: 'Bug Report'
description: 'Submit a bug report'
body:
  - type: 'textarea'
    id: 'description'
    attributes:
      label: 'Description'
      description: 'A clear and concise description of what the bug is.'
      placeholder: |
        Bug description
    validations:
      required: true
  - type: 'textarea'
    id: 'reproduction_steps'
    attributes:
      label: 'Steps to reproduce'
      description: |
        Steps to reproduce the behavior:
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: 'input'
    id: 'expected_behavior'
    attributes:
      label: 'Expected behavior'
      description: 'A clear and concise description of what you expected to happen.'
    validations:
      required: true
  - type: 'input'
    id: 'lib-version'
    attributes:
      label: 'Hidabroot API Version'
      description: 'The version of the package you used (you can run `npm list hidabroot` to find it).'
    validations:
      required: true
  - type: 'input'
    id: 'lib-version'
    attributes:
      label: 'Puppeteer Version'
      description: 'The version of puppeteer you are using (you can run `npm list puppeteer` to find it).'
    validations:
      required: true
  - type: 'checkboxes'
    id: 'operating-system'
    attributes:
      label: 'Operating System'
      description: 'The operating system(s) this issue occurred with.'
      options:
        - label: 'macOS'
        - label: 'Windows'
        - label: 'Linux'
    validations:
      required: true